import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import MarketPLace from "@/app/trending-collection/page";
import Rankings from "@/app/top-creator/page";
import BrowseCategories from "@/app/browse-categories/page";
import DiscoverBrowser from "@/app/discover-more/page";
import MagicMashrooms from "@/app/magic-mashrooms/page";
import HowItWorks from "@/app/how-it-works/page";
import Article from "@/components/article";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen flex flex-col justify-between">
          <Header />
          <main className="flex justify-center">{children}</main>
          <main>
            <MarketPLace />
          </main>
          <main>
            <Rankings />
          </main>
          <main>
            <BrowseCategories />
          </main>
          <main>
            <DiscoverBrowser />
          </main>
          <main>
            <MagicMashrooms />
          </main>
          <main>
            <HowItWorks />
          </main>
          <main>
            <Article />
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
